### ISSUE TITLE
Release v1.5 does not pass Windows Defender scan test

### ISSUE THREAD

**Issue by ekrekeler** [pbatard/winpatch#6]
When downloading [release v1.5](https://github.com/pbatard/winpatch/releases/tag/v1.5) of this software, Windows Defender marks it as a virus and prevents saving the file.

It is marked Trojan:Win32/Fuery.C!cl
Full report: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fFuery.C!cl&threatid=2147718736

**Comment by pbatard** [comment]
It's the usual false positive plague...

When you are patching Windows system files, you find that "security" solutions tend not to like that.

I seriously could **not** be more open about building the executable to remove the slighted possibility that it's malicious:
See the lines that say:
```
Algorithm : SHA256
Hash      : 709552D477C6FF0A4D8A9F28E94917AE27807EE2EC1BED227CAD1C357696937D
Path      : C:\projects\winpatch\winpatch.zip
```
in the [lastest AppVeyor log](https://ci.appveyor.com/project/pbatard/winpatch)?
This is the SHA-256 of the zip file that was built from the AppVeyor servers. Compare that with the SHA-256 of the file you download from the release you pointed to, and you will find that it **matches exactly**.

So, that means that, unless I have found a way to hack AppVeyor to falsify their build log, there is no shadow of a doubt that the executable you got was built by an automated system that is 100% outside of my control, and therefore that, even if I really wanted to, I simply cannot insert a hidden malware into the `winpatch.exe` you downloaded and that your antivirus software alleged contains a Trojan.

Which means one of two things exclusively:
1. Either the Trojan, if there exists one, **must** exist in the git source repository of the commit that triggered the build, in which case it should be **exceedingly easy** for someone to point to it, as there is simply no possibility that the malicious behaviour could be hidden. And considering that the source is very simple and doesn't rely on any external dependency or doesn't download anything to exectute, there's really no way that alleged "Trojan" could be hidden anywhere but in the very public source I publish here. So where is it?
2. Either Windows Defender is wrongly classifying a non-malicious application as containing a Trojan.

Clearly then, Windows Defender is wrong. And since I am exceedingly tired of having about [half the software I publish](https://www.virustotal.com/gui/file/a43bf34285d393f843b05d80f74c4790ed7f6ac636393ca5f6375ae0bb02e719/detection) being **WRONGLY** classified as a Trojan by antivirus vendors who should know a lot better, I will ask you to complain to Microsoft directly if you are unhappy about the situation and close this issue.

**Comment by pbatard** [comment]
For what is worth, it appears that Windows Defender [have finally cleared their FALSE POSITIVE](https://www.virustotal.com/gui/file/4da42f3a91b9d96c1838716f6e1b6c5626a83e5ebc67a8fcd45fee888e40662a/detection).

**Comment by ekrekeler** [comment]
Hey @pbatard ,
Yes I wasn't calling this a virus at all, I work in the security field and I understand well the nature of false positives. That's why I was trying to be careful with how I worded it.

Glad that it got cleared up!
